version: '2'

services:
    sensu-uchiwa:
      container_name: sensu-uchiwa
      restart: always
      image: sstarcher/uchiwa:0.15.0
      networks:
        - backbone
      environment:
        SENSU_HOSTNAME: sensu-api
        SENSU_DC_NAME: Sensu
      ports:
        - "3000:3000"

    sensu-api:
      container_name: sensu-api
      restart: always
      image: accenture/adop-sensu:0.1.0
      networks:
        - backbone
      command: api
      expose:
        - "4567"
      environment:
        RABBITMQ_HOST: sensu-rabbitmq
        REDIS_HOST: sensu-redis
      volumes:
        - sensu_api_conf:/etc/sensu/conf.d

    sensu-server:
      container_name: sensu-server
      restart: always
      image: accenture/adop-sensu:0.1.0
      networks:
        - backbone
      command: server
      environment:
        CLIENT_NAME: core
        API_HOST: sensu-api
        RABBITMQ_HOST: sensu-rabbitmq
        REDIS_HOST: sensu-redis
      volumes:
        - sensu_server_conf:/etc/sensu/conf.d
        - sensu_server_checks:/etc/sensu/check.d
        - sensu_server_handlers:/etc/sensu/handlers

    sensu-client:
      container_name: sensu-client
      restart: always
      image: accenture/adop-sensu:0.1.0
      networks:
        - backbone
      command: client
      environment:
        CLIENT_NAME: core
        RABBITMQ_HOST: sensu-rabbitmq
        JENKINS_PREFIX: jenkins
        CLIENT_SUBSCRIPTIONS: "proxy,gerrit,jenkins,nexus,sonarqube,sensu,kibana"
      volumes:
        - sensu_client_plugins:/etc/sensu/plugins

    sensu-client-nexus:
      container_name: sensu-client-nexus
      restart: always
      image: accenture/adop-sensu:0.1.0
      networks:
        - backbone
      command: client
      environment:
        CLIENT_NAME: nexus
        RABBITMQ_HOST: sensu-rabbitmq
        JENKINS_PREFIX: jenkins
        CLIENT_SUBSCRIPTIONS: "nexus"
      volumes:
        - sensu_client_plugins:/etc/sensu/plugins

    sensu-client-jenkins:
      container_name: sensu-client-jenkins
      restart: always
      image: accenture/adop-sensu:0.1.0
      networks:
        - backbone
      command: client
      environment:
        CLIENT_NAME: jenkins
        RABBITMQ_HOST: sensu-rabbitmq
        JENKINS_PREFIX: jenkins
        CLIENT_SUBSCRIPTIONS: "jenkins"
      volumes:
        - sensu_client_plugins:/etc/sensu/plugins

    sensu-client-gerrit:
      container_name: sensu-client-gerrit
      restart: always
      image: accenture/adop-sensu:0.1.0
      networks:
        - backbone
      command: client
      environment:
        CLIENT_NAME: gerrit
        RABBITMQ_HOST: sensu-rabbitmq
        JENKINS_PREFIX: jenkins
        CLIENT_SUBSCRIPTIONS: "gerrit"
      volumes:
        - sensu_client_plugins:/etc/sensu/plugins

    sensu-rabbitmq:
      container_name: sensu-rabbitmq
      restart: always
      image: rabbitmq:3.5.7-management
      networks:
        - backbone
      expose:
        - "5672"
        - "5671"
        - "15672"
        - "15671"
      volumes:
        - sensu_rabbitmq_data:/var/lib/rabbitmq

    sensu-redis:
      container_name: sensu-redis
      restart: always
      image: redis:3.0.7
      networks:
        - backbone
      expose:
        - "6379"
      volumes:
        - sensu_redis_data:/data

networks:
    backbone:
      external:
        name: ${CUSTOM_NETWORK_NAME}

volumes:
    sensu_api_conf:
      driver: local
    sensu_server_conf:
      driver: local
    sensu_client_conf:
      driver: local
    sensu_server_conf:
      driver: efs
      driver_opts:
        share: ${Sensu_EFS_VolumeId}/sensu-server/conf.d
    sensu_server_checks:
      driver: efs
      driver_opts:
        share: ${Sensu_EFS_VolumeId}/sensu-server/check.d
    sensu_server_handlers:
      driver: efs
      driver_opts:
        share: ${Sensu_EFS_VolumeId}/sensu-server/handlers
    sensu_client_plugins:
      driver: efs
      driver_opts:
        share: ${Sensu_EFS_VolumeId}/sensu-client/plugins
    sensu_rabbitmq_data:
      driver: local
    sensu_redis_data:
      driver: local
